# Generated by Django 5.2.7 on 2025-11-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True)),
                ('comentario', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='perfis/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
