# Generated by Django 5.2.7 on 2025-11-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('reputacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('telefone', models.CharField(max_length=15)),
                ('e_vendedor', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=50)),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
