# Generated by Django 5.2.7 on 2025-11-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='localVenda',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=200)),
                ('pagamento', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previsao_ent', models.DateField()),
                ('id_book_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
                ('id_user_compFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='usuario.usuario')),
                ('id_user_vendFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='usuario.usuario')),
            ],
        ),
    ]
