# Generated by Django 5.2.7 on 2025-11-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('total_pag', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('id_user_cadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
