# Generated by Django 5.2.7 on 2025-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('total_pag', models.IntegerField()),
            ],
        ),
    ]
